### ISSUE TITLE
Icon=system-file-manager is still displayed with the old Mint-Y green

### ISSUE THREAD

**Issue by SebastJava** [SebastJava/mint-yz-icons#3]
@leonp5 wrote:
Thanks for your work :)
[...]
I use the Darker-MintSoft Theme and recocgnized that a the folder icon(?) still have the color from MintSoda. Using LM 20 with Xfce.
Also in the xfce panel and in puddletag the folder icon has the MintSoda color. But in thunar, for example, it has the correct MintSoft color.
![Screenshot from 2021-01-15 15-01-33](https://user-images.githubusercontent.com/31940713/104773191-aacdbc80-5742-11eb-882d-3b6be707b8f9.png)
(These comments are copy-pasted from the "pull request" section because there was no issue section available at the time...)

**Comment by SebastJava** [comment]
@leonp5 Thank you for submitting this issue. I knew this already, 4 days ago, and i had put a notice in the Readme file here about this. I am currently working on this today and i hope i will make a new release available sometime within 72 hours from now. Fixing this could probably be simple, but when i looked at it, i saw there were lots of other updates made to the upstream source.
So, i will make a full update. Stay tuned !

**Comment by SebastJava** [comment]
@leonp5 Sorry for the long delay. I made lots of changes. Check the description on the releases page. Feedback, please.

**Comment by leonp5** [comment]
@SebastJava on every occunrences where i detected the "wrong" green, it is now correct. Thanks a lot :)
